service: dreamcast-api
frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

# employees-table-dev
custom:
  employeesTableName: "employees-table-${sls:stage}"
  selfAssesmentTableName: "self-assesments-table-${sls:stage}"
  managerAssesmentTableName: "manager-assesments-table-${sls:stage}"
  developmentPlanTableName: "development-plans-table-${sls:stage}"
  dynamodb:
    stages:
      - dev

provider:
  httpApi:
    cors: true
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  profile: default # You'll have to create your own profile with IAM creds to your AWS account

  iam: # Role is applied globally to all functions below allowing access to dynamodb table JobsTable
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [JobsTable, Arn]

functions:
  listItems:
    handler: lambdas/listItems.listItems
    events:
      - httpApi:
          path: /{model}
          method: get
    environment:
      EMPLOYEES_TABLE: ${self:custom.employeesTableName}
      DEVELOPMENT_PLAN_TABLE: ${self:custom.developmentPlanTableName}
      MANAGER_ASSESSMENT_TABLE: ${self:custom.managerAssesmentTableName}
      SELF_ASSESSMENT_TABLE: ${self:custom.selfAssesmentTableName}
      # add any other table names below here

  getItem:
    handler: lambdas/getItem.getItem
    events:
      - httpApi:
          path: /{model}/{id}
          method: get
    environment:
      EMPLOYEES_TABLE: ${self:custom.employeesTableName}
      DEVELOPMENT_PLAN_TABLE: ${self:custom.developmentPlanTableName}
      MANAGER_ASSESSMENT_TABLE: ${self:custom.managerAssesmentTableName}
      SELF_ASSESSMENT_TABLE: ${self:custom.selfAssesmentTableName}
      # add any other table names below here

  updateItem:
    handler: lambdas/updateItem.updateItem
    events:
      - httpApi:
          path: /{model}/{id}
          method: patch
    environment:
      EMPLOYEES_TABLE: ${self:custom.employeesTableName}
      DEVELOPMENT_PLAN_TABLE: ${self:custom.developmentPlanTableName}
      MANAGER_ASSESSMENT_TABLE: ${self:custom.managerAssesmentTableName}
      SELF_ASSESSMENT_TABLE: ${self:custom.selfAssesmentTableName}

  deleteItem:
    handler: lambdas/deleteItem.deleteItem
    events:
      - httpApi:
          path: /{model}/{id}
          method: delete
    environment:
      EMPLOYEES_TABLE: ${self:custom.employeesTableName}
      DEVELOPMENT_PLAN_TABLE: ${self:custom.developmentPlanTableName}
      MANAGER_ASSESSMENT_TABLE: ${self:custom.managerAssesmentTableName}
      SELF_ASSESSMENT_TABLE: ${self:custom.selfAssesmentTableName}

  createEmployee:
    handler: lambdas/createItems/createEmployee.createEmployee
    events:
      - httpApi:
          path: /employees
          method: post
    environment:
      EMPLOYEES_TABLE: ${self:custom.employeesTableName}

  createDevelopmentPlan:
    handler: lambdas/createItems/createDevelopmentPlan.createDevelopmentPlan
    events:
      - httpApi:
          path: /development-plan
          method: post
    environment:
      DEVELOPMENT_PLAN_TABLE: ${self:custom.developmentPlanTableName}

  createManagerAssesment:
    handler: lambdas/createItems/createManagerAssessment.createManagerAssessment
    events:
      - httpApi:
          path: /manager-assessment
          method: post
    environment:
      MANAGER_ASSESSMENT_TABLE: ${self:custom.managerAssesmentTableName}

  createSelfAssesment:
    handler: lambdas/createItems/createSelfAssessment.createSelfAssessment
    events:
      - httpApi:
          path: /self-assessment
          method: post
    environment:
      SELF_ASSESSMENT_TABLE: ${self:custom.selfAssesmentTableName}

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.employeesTableName}
    SelfAssesmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.selfAssesmentTableName}
    ManagerAssesmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.managerAssesmentTableName}
    DevelopmentPlanTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.developmentPlanTableName}
